### ISSUE TITLE
Add the "flying button" return to yunohost main page

### ISSUE THREAD

**Issue by Jibec** [mbugeia/kanboard_ynh#10]
May you add the return button to YNH main page ? You can see this button on other official app like TTRSS

**Comment by mbugeia** [comment]
That's a bug, the javascript code for the panel is loaded but not executed because of the Content Security Policy header sent by Kanboard.

Error message:
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
domReady @ ynhpanel.js:173

This can be avoided by patching this line of kanboard source file:
https://github.com/fguillot/kanboard/blob/9c9ed02cd7ebc5dbbc99bcaed6f80988ce8a9677/app/Core/Response.php#L219
to
$policies['default-src'] = "'self' 'unsafe-eval' data:";

But even after that, we can see the button but it doesn't work...

**Comment by mbugeia** [comment]
Fixed in the last commit

**Comment by Jibec** [comment]
it works fine, thank you !
